Fixes
MeowerBots/.github pull request #8
Opened 2023-02-24 13:41 UTC by JoshAtticus

2023-02-24 14:03 UTC, showierdata9978 commented
Should allow for changing the prefix, because of stuff like webhooks (`@HookMod`) and CodeBot setting it's prefix by default

2023-02-24 14:22 UTC, showierdata9978 requested changes
^

2023-02-25 01:35 UTC, JoshAtticus commented
Done

2023-02-25 02:25 UTC, showierdata9978 approved these changes

2023-02-25 02:25 UTC, merged